world_name: brsu

plugins:
  - name: laser_integration
    lib: libed_laser_plugin_tracking.so
    frequency: 30
    parameters:
        laser_topic: /ropod/laser/scan
        min_segment_size_pixels: 6
        world_association_distance: 0.2
        segment_depth_threshold: 0.08
        min_cluster_size: 0.05
        max_cluster_size: 10.0
        max_gap_size: 1
        min_gap_size_for_split: 5
        check_door_status: 1
        nominal_corridor_width: 0.5
        correctRot: 1
        correctTrans: 0
        dist_for_object_split: 0.4
#  - name: laser_integration2
#    lib: libed_laser_plugin_tracking2.so
#    frequency: 30
#    parameters:
#        laser_topic: /ropod/laser_back/scan
#        min_segment_size_pixels: 20
#        world_association_distance: 0.2
#        segment_depth_threshold: 0.08
#        min_cluster_size: 0.05
#        max_cluster_size: 10.0
#        max_gap_size: 10
#        min_gap_size_for_split: 10
#        check_door_status: 1
#        nominal_corridor_width: 0.5
#        correctRot: 1
#        correctTrans: 0
#        dist_for_object_split: 0.4

  - name: entity_clearer
    lib: libed_clearer_plugin.so
    enabled: 1
    parameters:
        entity_timeout: 3.0
#  - name: route_navigation
#    lib: libed_route_navigation_plugin.so
#    frequency: 5
#    parameters:
#        mobidik_initially_connected: 0
#        sensor_back: 0
#        rear_pointcloud_sensor: 1
  - name: gui_server
    lib: libed_gui_server_plugin.so
    parameters:
        predict_entities: 0
  - name: entity_server
    lib: libed_entity_server_plugin.so
    parameters:
        cart_mobidik_width: 0.72
        cart_mobidik_margin: 0.22
