TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: -0.2
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 2.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  meter_scoring: true

  holonomic_robot: true
  controller_frequency: 5.0
  pdist_scale: 3.0
  path_distance_bias: 100.0
  occdist_scale: 0.02
  latch_xy_goal_tolerance: true
  clearing_rotation_allowed: false
  
DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 2.0
  max_trans_vel: 1.5
  min_trans_vel: 0.1
  max_vel_x: 1.5
  min_vel_x: 0.0
  max_vel_y: 1.0
  min_vel_y: 0.0 
  max_rot_vel: 0.5
  min_rot_vel: 0.0
  
  controller_frequency: 5.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  
  path_distance_max: 0.2
  forward_point_distance: 0.1


global_frame: /map  

