map_type: costmap           # default: "voxel"

obstacle_range: 5.0
raytrace_range: 10.0

inflation_radius: 0.1
# robot_radius: 0.2


observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: /ropod/laser/scan, data_type: LaserScan, topic: /ropod/laser/scan, marking: true, clearing: true}   


